import type { Metadata } from "next";
import SideBar from "./components/sidebar";
import "./styles/reset/reset.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body>
        <SideBar />
        {children}
      </body>
    </html>
  );
}
